pipeline {
    agent any  

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/sid-sadhana/DO.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('firstcicd/myapp') {
                    sh 'npm install --no-fund --no-audit'
                }
            }
        }

        stage('Build React App') {
            steps {
                dir('firstcicd/myapp') {
                    sh 'npm run build'
                }
            }
        }

        stage('Serve React App') {
            steps {
                dir('firstcicd/myapp') {
                    sh '''
                    JENKINS_NODE_COOKIE=dontKillMe nohup serve -s build -l 3000 > serve.log 2>&1 &
                    '''
                }
            }
}

    }

    post {
        success {
            echo '✅ Deployment Successful!'
        }
        failure {
            echo '❌ Deployment Failed!'
        }
    }
}
